version: '3.8'
name: postgress_systems
services:
  postgress_db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=sarah
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=databaseschool
    ports:
      - '5433:5432'
    volumes:
      - postgress_db:/var/lib/postgresql/data
volumes:
  postgress_db:
    driver: local
networks:
  default:
    driver: bridge